# fly.toml app configuration file generated for telegram-chat-bot-api on 2023-06-01T18:21:04+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "telegram-chat-bot-api"
primary_region = "waw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1